#!/usr/bin/env python3
import rospy
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
from roboflow import Roboflow
import supervision as sv
import cv2
import numpy as np

def main():
    rospy.init_node('pallet_detection_publisher')

    # Initialize CvBridge
    bridge = CvBridge()

    # Publisher for annotated image
    image_pub = rospy.Publisher('/pallet_detection/image', Image, queue_size=10)

    # Initialize Roboflow
    rf = Roboflow(api_key="LlIKXYgtTmJZ2CUwv4Hl")
    project = rf.workspace().project("pallet-5esjz")
    model = project.version(1).model

    # create instance of BoxAnnotator
    box_annotator = sv.BoxAnnotator(thickness=4, text_thickness=4, text_scale=2)

    # Open a video file or stream
    video_capture = cv2.VideoCapture("/home/ali/Pallets_Grad_Data/pallets3.mp4")  # Corrected file path

    # Check if the video capture is open
    if not video_capture.isOpened():
        print("Error: Unable to open video source.")
        return

    # Loop for processing frames
    rate = rospy.Rate(30)  # Adjust as needed
    while not rospy.is_shutdown():
        # Read a frame from the video
        ret, frame = video_capture.read()
        if not ret:
            print("Error: Unable to read frame.")
            break

        # Predict on the frame
        results = model.predict(frame).json()
        detections = sv.Detections.from_roboflow(results)

        # Print the structure of detections
        print(detections)

        labels = [
            f"{detections.data['class_name'][class_id - 1]} {confidence:0.2f}"
            for confidence, class_id
            in zip(detections.confidence, detections.class_id)
        ]

        # Annotate the frame
        annotated_frame = box_annotator.annotate(scene=frame, detections=detections, labels=labels)

        # Convert the annotated frame from BGR to RGB format
        annotated_frame_rgb = cv2.cvtColor(annotated_frame, cv2.COLOR_BGR2RGB)

        # Convert the annotated frame to ROS Image message
        image_msg = bridge.cv2_to_imgmsg(annotated_frame_rgb, encoding="rgb8")

        # Publish the annotated frame
        image_pub.publish(image_msg)

        rate.sleep()

    # Release the video capture
    video_capture.release()

if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass
