<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="apjr">
    <!-- ################################### Definitions  #####################################-->



    <xacro:include filename="$(find apjr_bringup)/robot_description/urdf/apjr.gazebo"/>
    <xacro:include filename="$(find apjr_bringup)/robot_description/urdf/physicalProperties.xacro"/>
    <xacro:include filename="$(find apjr_bringup)/robot_description/urdf/functions.xacro"/>
    <xacro:include filename="$(find apjr_bringup)/robot_description/urdf/joints.xacro"/>
    <xacro:include filename="$(find apjr_bringup)/robot_description/urdf/transmission.xacro"/>


    

    <!-- ################################### base_footprint #####################################-->
    <!-- base_footprint is a fictious link(frame) that is on the ground right below base_link origin -->
    <!-- It is necessary as gazebo does not support inertia for the root link -->
    <!-- Do not call it cs as it is reserved for robot that must be fixed to the world -->

   <link name="base_footprint">
    </link>

    <!-- ################################### Chassis Link #####################################-->

    <link name="chassis">
        <inertial>
            <xacro:chassis_inertial/>
        </inertial>
        <visual name="chassis">
            <xacro:chassis_geometry/>
            <material name="">
                <color rgba="1.0 0.0 0.0 1.0"/>
                <texture filename=""/>
            </material>
        </visual>
        <collision>
            <xacro:chassis_geometry/>
        </collision>
    </link>
    <xacro:fixed_offset_joint parent="base_footprint" child="chassis" offset="0 0 ${chassisHeight/2 + 0.16}"/> 

     <!-- ################################### Right Fork Caster Wheel link #####################################-->

    <link name="right_chassis_caster_wheel">
        <inertial>
            <xacro:casterWheel_inertial/>
        </inertial>
        <visual name="right_chassis_caster_wheel">      
            <xacro:casterWheel_geometry/>
        </visual>  
        <collision name="right_chassis_caster_wheel">
            <xacro:casterWheel_geometry/>
             <surface>        
            <friction>          
                <ode>            
                <mu>0</mu>            
                <mu2>0</mu2>            
                <slip1>0.0</slip1>            
                <slip2>0.0</slip2>          
                </ode>        
            </friction>      
            </surface>   
        </collision>
    </link>
    <xacro:wheel_joint parent="chassis" child="right_chassis_caster_wheel" offset="0.0 ${-chassisWidth/2 + forkWidth/2} ${-chassisHeight/2 + casterRadius -wheelRadius*2}" axis="0 1 0"/>
         <!-- ################################### Right Fork Caster Wheel link #####################################-->

    <link name="left_chassis_caster_wheel">
        <inertial>
            <xacro:casterWheel_inertial/>
        </inertial>
        <visual name="right_chassis_caster_wheel">      
            <xacro:casterWheel_geometry/>
        </visual>  
        <collision name="right_chassis_caster_wheel">
            <xacro:casterWheel_geometry/>
            <surface>        
            <friction>          
                <ode>            
                <mu>0</mu>            
                <mu2>0</mu2>            
                <slip1>0.0</slip1>            
                <slip2>0.0</slip2>          
                </ode>        
            </friction>      
            </surface>   
        </collision>
    </link>
    <xacro:wheel_joint parent="chassis" child="left_chassis_caster_wheel" offset="0.0 ${chassisWidth/2 - forkWidth/2} ${-chassisHeight/2 + casterRadius -wheelRadius*2}" axis="0 1 0"/>
    <!-- ################################### Right Fork Link #####################################-->

    <link name="fork_right">
        <inertial>
            <xacro:fork_inertial/>
        </inertial>
        <visual name="fork_right">
            <xacro:fork_geometry/>
            <material name="">
                <color rgba="0.173 0.216 0.230 1.0"/>
                <texture filename=""/>
            </material>
        </visual>
        <collision>
            <xacro:fork_geometry/>
        </collision>
    </link>
    <xacro:fixed_offset_joint parent="chassis" child="fork_right" offset="${chassisLength/2 + forkLength/2} ${-chassisWidth/2 + forkWidth/2} ${-chassisHeight/2 + forkHeight/2}"/>
        <!-- ################################### Right Fork Caster Wheel link #####################################-->

    <link name="right_fork_caster_wheel">
        <inertial>
            <xacro:casterWheel_inertial/>
        </inertial>
        <visual name="right_fork_caster_wheel">      
            <xacro:casterWheel_geometry/>
        </visual>  
        <collision name="right_fork_caster_wheel">
            <xacro:casterWheel_geometry/>
            <surface>        
            <friction>          
                <ode>            
                <mu>0</mu>            
                <mu2>0</mu2>            
                <slip1>0.0</slip1>            
                <slip2>0.0</slip2>          
                </ode>        
            </friction>      
            </surface>   
        </collision>
    </link>
    <xacro:wheel_joint parent="chassis" child="right_fork_caster_wheel" offset="${chassisLength/2 + forkLength/2 + 0.2} ${-chassisWidth/2 + forkWidth/2} ${-chassisHeight/2 + casterRadius -wheelRadius*2}" axis="0 1 0"/>

    <!-- ################################### Left Fork Link #####################################-->

    <link name="fork_left">
        <inertial>
            <xacro:fork_inertial/>
        </inertial>
        <visual name="fork_left">
            <xacro:fork_geometry/>
            <material name="">
                <color rgba="0.173 0.216 0.230 1.0"/>
                <texture filename=""/>
            </material>
        </visual>
        <collision>
            <xacro:fork_geometry/>            
        </collision>
        
    </link>
    <xacro:fixed_offset_joint parent="chassis" child="fork_left" offset="${chassisLength/2 + forkLength/2} ${chassisWidth/2 - forkWidth/2} ${-chassisHeight/2 + forkHeight/2}"/>
    <!-- ################################### Left Fork Caster Wheel link #####################################-->

    <link name="left_fork_caster_wheel">
        <inertial>
            <xacro:casterWheel_inertial/>
        </inertial>
        <visual name="left_fork_caster_wheel">      
            <xacro:casterWheel_geometry/>
        </visual>  
        <collision name="left_fork_caster_wheel">
            <xacro:casterWheel_geometry/>
            <surface>        
            <friction>          
                <ode>            
                <mu>0</mu>            
                <mu2>0</mu2>            
                <slip1>1.0</slip1>            
                <slip2>1.0</slip2>          
                </ode>        
            </friction>      
            </surface>   
        </collision>
    </link>
    <xacro:wheel_joint parent="chassis" child="left_fork_caster_wheel" offset="${chassisLength/2 + forkLength/2 + 0.2} ${chassisWidth/2 - forkWidth/2} ${-chassisHeight/2 + casterRadius -wheelRadius*2}" axis="0 1 0"/> 

    <!-- ################################### Shaft link #####################################-->    

    	<!-- <link name="drive_wheel_shaft">
		<visual>
			<material name="black"/>
			<xacro:shaft_geometry/>
		</visual> -->
		<!-- <collision>
			<xacro:shaft_geometry/>
		</collision> -->
		<!-- <inertial>
			<xacro:shaft_inertial/>
		</inertial>
	</link> -->
	<!-- <xacro:fixed_offset_joint parent="chassis" child="drive_wheel_shaft" offset="0.0 0.0 ${-chassisHeight/2 - wheelRadius}"/> -->

    <!-- ################################### Hinge link #####################################-->    
    <link name="drive_wheel_hinge">
		<visual>
			<!-- <material name="white"/> -->
			<xacro:hinge_geometry/>
		</visual>
		<!--<collision>
			<xacro:hinge_geometry/>
		</collision>-->
		<inertial>
			<!-- <xacro:hinge_inertial/> -->
            <mass value="0.05" />
		<inertia ixx="0"
			 ixy="0"
			 ixz="0"
			 iyy="0"
			 iyz="0"
			 izz="${2/5*0.05*(0.015*0.015)}"
		/>
		</inertial>
	</link>
    <joint name="steering_joint" type="revolute">
        <origin xyz="0.0 0.0 ${-chassisHeight/2 - wheelRadius}" rpy="0 0 0"/>
        <parent link="chassis"/>
        <child link="drive_wheel_hinge"/>
        <axis xyz="0 0 1"/>
        <limit lower="-1.570796" upper="1.570796" effort="1000000" velocity="100"/>
        <joint_properties damping="1.0" friction="1.0"/>
        <dynamics damping="1" friction="0"/> 
    </joint>

	<!-- <xacro:hinge_joint parent="chassis" child="drive_wheel_hinge" offset="0.0 0.0 ${-chassisHeight/2 - wheelRadius}"/> -->
	<xacro:hinge_transmission hinge="steering"/>
    
    <!-- ################################### Drive Wheel link #####################################-->

    <link name="drive_wheel">
        <inertial>
            <xacro:driveWheel_inertial/>
        </inertial>
        <visual name="drive_wheel">
            <xacro:driveWheel_geometry/>
            <material name="">
                <color rgba="0.3 1.0 0.0 1.0"/>
                <texture filename=""/>
            </material>
        </visual>
        <collision>
            <xacro:driveWheel_geometry/>
            <surface>        
                <friction>          
                    <ode>            
                    <mu>0</mu>            
                    <mu2>0</mu2>            
                    <slip1>0.0</slip1>            
                    <slip2>0.0</slip2>          
                    </ode>        
                </friction>   
                <contact>
                    <ode>
                    <kp>1e15</kp>
                    <kd>1e13</kd>
                    </ode>
                </contact>
            </surface>   
        </collision>
    </link>
	<xacro:wheel_transmission wheel="drive_wheel"/>
    <!-- ################################### Joints #####################################-->

    <joint name="drive_wheel_joint" type="continuous">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <!-- <origin xyz="0.0 0.0 ${-chassisHeight/2 - wheelRadius} " rpy="0.0 0.0 0.0"/> -->
        <parent link="drive_wheel_hinge"/>
        <child link="drive_wheel"/>
        <axis xyz="0.0 1.0 0.0"/>
       <!-- <limit lower="0" upper="0.0" effort="1000000" velocity="1000.0"/>
       <joint_properties damping="0.5" friction="1"/> -->
        <!-- <limit lower="0" upper="0" effort="10" velocity="1000.0"/>
       <joint_properties damping="1.0" friction="1.0"/>
       <dynamics damping="1" friction="0"/> -->
       
    </joint>
    <!-- ################################### base_scan Link #####################################-->
    <link name="base_scan">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <!-- <mesh filename="package://robotTrial_description/meshes/hokuyo.dae"/> -->
            <box size="0.1 0.1 0.1"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="hokuyo_joint" type="fixed">
        <axis xyz="0 1 0" />
        <origin xyz="0 0 ${chassisHeight/2 + 0.05}" rpy="0 0 0"/>
        <parent link="chassis"/>
        <child link="base_scan"/>
    </joint>  



<joint name="imu_joint" type="fixed">
    <parent link="chassis"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
</joint>

  <link name="imu_link"/>
</robot>